title: Places to hike
theme: jekyll-theme-tactile
description: >- # this means to ignore newlines until "baseurl:"
  Hiking information.
baseurl: "" # the subpath of your site, e.g. /blog
# Build settings
markdown: kramdown
theme: minima
# plugins:
#    - jekyll-maplinks
exclude:
  - .git/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
